project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - publications_stat.qmd
    - publications_med.qmd
    - textbook.qmd
    - software.qmd
    - talks.qmd
    - teaching.qmd
    - working.qmd
    - posts.qmd
    - roche_ds.qmd
    - podcasts.qmd
    - code/
    - conference.qmd
    
website:
  title: "Kaspar Rufibach, biostatistician"
  navbar:
    background: info
    left:
    - text: "Publications"
      menu:
        - text: "Statistical methodological publications"  
          href: publications_stat.html
        - text: "Biostatistical textbook"
          href: textbook.html
        - text: "Biomedical publications"  
          href: publications_med.html
    - text: "Software"
      href: software.html
    - text: "Podcasts"
      href: podcasts.html
    - text: "Talks"
      href: talks.html
    - text: "Teaching & supervision"
      href: teaching.html
    - text: "Working groups"
      href: working.html
    - text: "Conference organization"
      href: conference.html
    - text: "Posts"
      href: posts.html
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source