---
title: ""
date: last-modified
output: 
  rmarkdown::html_document:
    highlight: pygments
    number_sections: yes
    self_contained: yes
    toc: yes
    toc_depth: 2
    toc_float: yes
format: html
tbl-colwidths: [7,20,50,13]
---

# Status of this page

This page is still under construction, I keep adding talks, mainly those for which I provide slides.

A pdf file listing all my talks can be [downloaded](files/03_Kaspar_Rufibach_talks.pdf).

# Talks for download

```{r setup, include = FALSE, echo = FALSE}
## load packages
packs.html <- c("knitr", "pander", "reporttools", "dplyr", "readxl")
for (i in 1:length(packs.html)){library(packs.html[i], character.only = TRUE)}

knitr::opts_chunk$set(echo = TRUE)

## read in data
path <- getwd()
talks <- as.data.frame(read_excel(paste(path, "/data/talks.xlsx", sep = ""), col_types = NULL))
```

```{r echo = FALSE, message = FALSE, warning = FALSE, include = FALSE}
# how to do this with child documents: https://gist.github.com/rmoff/a043676a2f084b81a434
out1 <- NULL
ut <- unique(talks$Type)

for (j in 1:length(ut)){
    out1 <- c(out1, knit_expand('tools/talks.qmd'))
}

# the "knit" command somehow produces unwanted output, this is why I assign its output to a and use a separate chunk to display a

a <- knit(text = unlist(paste(out1, collapse = '\n')), quiet = TRUE)
```

```{r conferences, echo = FALSE, message = FALSE, warning = FALSE, results = "asis"}
cat(a)
```