---
title: ""
date: last-modified
output: 
  rmarkdown::html_document:
    highlight: pygments
    number_sections: yes
    self_contained: yes
    toc: yes
    toc_depth: 2
    toc_float: yes
---

# Upcoming courses

The German and Austrian-Swiss Region of the International Biometric Society together with the Austrian Statistical Society, the Intelligent Data Analytics Lab Salzburg and the Research Center Trustworthy Data Science and Security, UA Ruhr jointly organize a

*Summer School on Time-to-Event-Analysis*

in Strobl, Lake Wolfgang (Wolfgangsee).

Topics will range from practice-oriented to methodological and, e.g., cover an introduction to time-to-event-analysis as well as lectures on clinical trials with time-to-event endpoints, logistic regression with right censored (survival) data and strategies to model survival data beyond proportional hazards model.

Lectures will be given by four well-known authorities on time-to-event
analysis and its application

- *Paul Blanche* (København)
- *Sarah Friedrich* (Augsburg)
- *Kaspar Rufibach* (Basel)
- *Helga Wagner* (Linz)

and there will be plenty of room for informal discussions with the experts.

[download flyer](files/announcements/20240629_Wolfgangsee.pdf)


# Teaching and supervision

This page is still under construction.

Meanwhile, a pdf file listing all my talks can be [downloaded](files/04_Kaspar_Rufibach_teaching.pdf).

