{
  "hash": "f4067192cf08108e3c4900c9032f375a",
  "result": {
    "markdown": "---\ntitle: \"Tatsächliche Kosten in Abhängigkeit der Arztkosten\"\nauthor: \n- name: Kaspar Rufibach\n  affiliation: Meiringen\ndate-modified: last-modified\nexecute:   \n  freeze: auto  # re-render only when source changes\noutput: \n  rmarkdown::html_document:\n    highlight: pygments\n    number_sections: yes\n    self_contained: yes\n    toc: yes\n    toc_depth: 3\n    toc_float: yes\n---\n\n\n\n\n# Rohdaten\n\nKPT Prämien für Hausarztmodell für 2024. KPT scheint die Franchise Sfr 2000 nicht anzubieten.\n\n\n::: {.cell}\n::: {.cell-output-display}\n| Franchise| Monatsprämie| Jahresprämie|\n|---------:|------------:|------------:|\n|       300|          431|         5172|\n|       500|          420|         5040|\n|      1000|          393|         4716|\n|      1500|          366|         4392|\n|      2000|           NA|           NA|\n|      2500|          311|         3732|\n:::\n:::\n\n\n# Ausgaben in Abhängigkeit der Arztkosten\n\nDie Grafik unten zeigt:\n\n- $x$-Achse: die verursachten Arzt- und Spitalkosten.\n- $y$-Achse: die tatsächlich zu bezahlenden Kosten, für jede Franchise.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](kpt2024_files/figure-html/unnamed-chunk-2-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n# Lesebeispiel\n\nWenn ich pro Jahr 4000 Sfr Arztkosten verursache, dann habe ich die folgenden Ausgaben, abhängig von der Franchise:\n\n\n::: {.cell}\n::: {.cell-output-display}\n|  300|  500| 1000| 1500| 2000| 2500|\n|----:|----:|----:|----:|----:|----:|\n| 5842| 5890| 6016| 6142|   NA| 6382|\n:::\n:::\n\n\nMit der höchsten Franchise ist für Kosten von Sfr 4000 mein maximales Risiko im Vergleich zur kleinsten Franchise 6382 - 5842 = 540. Solange meine Kosten aber unter Sfr 1900 bleiben fahre ich mit der höchsten Franchise in jedem Fall am besten.\n\nDas Maximum, das ich mit der höchsten Franchise mehr bezahle, erreiche ich ab Sfr 9500 Arztkosten und der Mehrbetrag ist 760. \n\n# Berechnung\n\nFür Arztkosten $x$ berechnen sich die Ausgaben gemäss \n\n$$\n\\text{Jahresprämie} + \\begin{cases}x & x < \\text{Franchise} \\\\ \\text{Franchise} + \\min\\{700; 0.1 \\cdot (x - \\text{Franchise})\\}& x \\ge \\text{Franchise}  \\end{cases}\n$$",
    "supporting": [
      "kpt2024_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}